session:
  mode: peer  # Mesh network

nodes:
  # Ping node (publisher example)
  - type: ping_node.PingNode  # Imports from ping_node.py
    params:
      robot_id: "myrobot"
      update_rate: 1.0  # Hz
      
  # Pong node (subscriber example)  
  - type: pong_node.PongNode  # Imports from pong_node.py  
    params:
      robot_id: "myrobot"
      response_delay: 0.2  # seconds 