session:
  mode: peer

nodes:
  - type: tide_driver_station.nodes.go2_sensors_node.Go2SensorsNode
    params:
      robot_id: cash
      update_rate: 20.0
      rerun_spawn: true
      rerun_app_id: go2/cash

scripts: []
